<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-DiscordBattleriteQueueEstimator-F7E98E97-F3CC-4AA3-98E4-5B2184AA5501</UserSecretsId>
    </PropertyGroup>
    <PropertyGroup>
        <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
        <!--        <PublishTrimmed>true</PublishTrimmed>-->
        <PublishAot>true</PublishAot>
        <SelfContained>true</SelfContained>
        <InvariantGlobalization>true</InvariantGlobalization>
        <InterceptorsNamespaces>$(InterceptorsPreviewNamespaces);Microsoft.EntityFrameworkCore.GeneratedInterceptors</InterceptorsNamespaces>
        <OptimizationPreference>Size</OptimizationPreference>
    </PropertyGroup>

    <ItemGroup>
        <!--        <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="10.0.10"/>-->
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <!--        <PackageReference Include="Microsoft.EntityFrameworkCore.Tasks" Version="10.0.12">-->
        <!--            <PrivateAssets>all</PrivateAssets>-->
        <!--            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
        <!--        </PackageReference>-->
        <PackageReference Include="NetCord" Version="1.0.0-beta.20"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DiscordBattleriteQueueEstimator.Shared\DiscordBattleriteQueueEstimator.Shared.csproj"/>
    </ItemGroup>
</Project>
