// <auto-generated />
using DiscordBattleriteQueueEstimator.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordBattleriteQueueEstimator.Shared.Migrations
{
    [DbContext(typeof(MyPoorLilContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DiscordBattleriteQueueEstimator.Shared.Data.Models.DbClearPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("DiscordBattleriteQueueEstimator.Shared.Data.Models.DbUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscordBattleriteQueueEstimator.Shared.Data.Models.DbUserMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastDate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartySize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score2")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartDate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Win")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserMatches");
                });

            modelBuilder.Entity("DiscordBattleriteQueueEstimator.Shared.Data.Models.DbUserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FakeRp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("DiscordBattleriteQueueEstimator.Shared.Data.Models.DbUserMatch", b =>
                {
                    b.HasOne("DiscordBattleriteQueueEstimator.Shared.Data.Models.DbUser", "User")
                        .WithMany("Matches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiscordBattleriteQueueEstimator.Shared.Data.Models.DbUserStatus", b =>
                {
                    b.HasOne("DiscordBattleriteQueueEstimator.Shared.Data.Models.DbUser", "User")
                        .WithMany("Statuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DiscordBattleriteQueueEstimator.Shared.Data.Models.RpInfo", "RpInfo", b1 =>
                        {
                            b1.Property<int>("DbUserStatusId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Details")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Hero")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("PartySize")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("DbUserStatusId");

                            b1.ToTable("Statuses");

                            b1.WithOwner()
                                .HasForeignKey("DbUserStatusId");
                        });

                    b.Navigation("RpInfo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiscordBattleriteQueueEstimator.Shared.Data.Models.DbUser", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
